<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="tests.weeder.WEEDERTests-20210727162516" tests="3" file="tests/weeder.py" time="42.761" timestamp="2021-07-27T16:26:05" failures="2" errors="0" skipped="0">
	<testcase classname="tests.weeder.WEEDERTests" name="test_WHEN_set_voltage_THEN_get_voltage_back_correctly" time="2.462" timestamp="2021-07-27T16:26:05" file="tests\weeder.py" line="42"/>
	<testcase classname="tests.weeder.WEEDERTests" name="test_WHEN_set_scurve_ramping_voltage_THEN_get_ramping_voltage_correctly" time="20.162" timestamp="2021-07-27T16:25:42" file="tests\weeder.py" line="46">
		<failure type="AssertionError" message="Expected PV, 'TE:NDW1799:WEEDER_01:RAMPVOLT_S' to have value '100' (type: 'int').
Final PV value was '0.0' (type: 'float')"><![CDATA[Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS\support\weeder\master\system_tests\tests\weeder.py", line 47, in test_WHEN_set_scurve_ramping_voltage_THEN_get_ramping_voltage_correctly
    self.ca.assert_setting_setpoint_sets_readback(100, "RAMPVOLT_S")
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 554, in assert_setting_setpoint_sets_readback
    self.assert_that_pv_is(readback_pv, expected_value, timeout=timeout)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 269, in assert_that_pv_is
    return self.assert_that_pv_value_causes_func_to_return_true(
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 248, in assert_that_pv_value_causes_func_to_return_true
    raise AssertionError(err)
AssertionError: Expected PV, 'TE:NDW1799:WEEDER_01:RAMPVOLT_S' to have value '100' (type: 'int').
Final PV value was '0.0' (type: 'float')
]]></failure>
	</testcase>
	<testcase classname="tests.weeder.WEEDERTests" name="test_WHEN_set_trapezoid_ramping_voltage_THEN_get_ramping_voltage_correctly" time="20.137" timestamp="2021-07-27T16:26:02" file="tests\weeder.py" line="44">
		<failure type="AssertionError" message="Expected PV, 'TE:NDW1799:WEEDER_01:RAMPVOLT_T' to have value '100' (type: 'int').
Final PV value was '0.0' (type: 'float')"><![CDATA[Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS\support\weeder\master\system_tests\tests\weeder.py", line 45, in test_WHEN_set_trapezoid_ramping_voltage_THEN_get_ramping_voltage_correctly
    self.ca.assert_setting_setpoint_sets_readback(100, "RAMPVOLT_T")
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 554, in assert_setting_setpoint_sets_readback
    self.assert_that_pv_is(readback_pv, expected_value, timeout=timeout)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 269, in assert_that_pv_is
    return self.assert_that_pv_value_causes_func_to_return_true(
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 248, in assert_that_pv_value_causes_func_to_return_true
    raise AssertionError(err)
AssertionError: Expected PV, 'TE:NDW1799:WEEDER_01:RAMPVOLT_T' to have value '100' (type: 'int').
Final PV value was '0.0' (type: 'float')
]]></failure>
	</testcase>
</testsuite>
